### ISSUE TITLE
Projeção

### ISSUE THREAD

**Issue by michelrodrigo** [lacsed/UltraDES#3]
Defini um autômato e fiz a projeção, como no código a seguir:

```
var s = Enumerable.Range(0, 20).Select(ii => new State($"s{ii}", ii == 0 ? Marking.Marked : Marking.Unmarked)).ToArray();

Event g = new Event("g", Controllability.Uncontrollable);
Event d = new Event("d", Controllability.Uncontrollable);
Event a = new Event("a", Controllability.Uncontrollable);
Event b = new Event("b", Controllability.Uncontrollable);
Event c = new Event("c", Controllability.Uncontrollable);
Event h = new Event("h", Controllability.Uncontrollable);
Event f = new Event("f", Controllability.Uncontrollable);

var G8 = new DeterministicFiniteAutomaton(new[]
{
	new Transition(s[0], c, s[1]),
	new Transition(s[1], d, s[2]),
	new Transition(s[2], e, s[3]),
	new Transition(s[3], f, s[4]),
	new Transition(s[0], a, s[5]),
	new Transition(s[5], b, s[6]),
	new Transition(s[6], g, s[4]),

  }, s[0], "G8");


G8.Projection(new[] {a, b, c, d, f, g}.ToArray()).ShowAutomaton("P");
```

O que eu fiz foi basicamente definir o seguinte autômato e em seguida fiz a projeção, mantendo apenas o evento "e".
![G](https://user-images.githubusercontent.com/12836843/94974655-96441c00-04e5-11eb-991d-7409ad168433.png)

O resultado obtido foi:

![P](https://user-images.githubusercontent.com/12836843/94974587-6a289b00-04e5-11eb-8b92-a1a027c766f7.png)

Se eu só mantive o evento "e" na projeção, os demais não deveriam aparecer em auto laço. Fiz a projeção em outro software e obtive o seguinte resultado, que eu acho que faz mais sentido:

![P2](https://user-images.githubusercontent.com/12836843/94974892-60536780-04e6-11eb-8388-5e026719d997.PNG)

**Comment by lucasvra** [comment]
This bug was corrected in the last update to the master branch and nuget package 2.2.1
